name: discord-components-core
org: skyra
install: true
packagePath: packages/core
identifierBase: false
tagTemplate: 'v{{new-version}}'
monoRepo: false
pushTag: true
gitRepo: skyra-project/discord-components
gitHostVariant: github
githubRelease: true
githubReleaseLatest: true
githubReleaseNameTemplate: '{{new-version}}'
